# AWS Configuration
aws:
  region: us-west-2
  profile: default
  account_id: "851454408197"
  
  # S3 Buckets
  s3:
    # Source bucket (MIMIC data on AWS Open Data)
    mimic_bucket: physionet-open
    
    # Your buckets (create these in AWS)
    output_bucket: "bergermimiciv"
    temp_bucket: "bergermimiciv"
    
  # Batch Configuration
  batch:
    compute_environment: mimic-preprocessing-env
    job_queue: mimic-preprocessing-queue
    job_definition: mimic-preprocess-job
    
    # Resource configuration
    max_vcpus: 256
    min_vcpus: 0
    desired_vcpus: 0
    instance_types:
      - optimal
    
  # EC2 Configuration
  ec2:
    # VPC settings (replace with your VPC)
    vpc_id: "vpc-xxxxx"
    subnet_ids:
      - "subnet-xxxxx"
      - "subnet-yyyyy"
    security_group_ids:
      - "sg-xxxxx"
      
  # IAM Roles (will be created)
  iam:
    batch_service_role: "BatchServiceRole"
    batch_instance_profile: "ecsInstanceRole"
    batch_job_role: "BatchJobRole"

# Docker Configuration
docker:
  ecr_repository: mimic-preprocessor
  image_tag: latest

# Data paths on S3
data_paths:
  # MIMIC-CXR-JPG dataset (images + metadata for deep learning)
  # This is the PRIMARY dataset for this project
  # Note: Version 2.1.0 uses 2.0.0 metadata filenames (not updated)
  mimic_cxr:
    bucket: "bergermimiciv"
    prefix: "mimic-cxr-jpg/2.1.0/"
    metadata: "mimic-cxr-2.0.0-metadata.csv.gz"  # Image metadata with StudyDate, StudyTime, ViewPosition
    split: "mimic-cxr-2.0.0-split.csv.gz"  # Train/val/test splits
    chexpert: "mimic-cxr-2.0.0-chexpert.csv.gz"  # CheXpert labels (14 diagnoses)
    negbio: "mimic-cxr-2.0.0-negbio.csv.gz"  # NegBio labels
    images: "files/"  # JPG images organized by patient (p10-p19)

  mimic_ed:
    bucket: "bergermimiciv"
    prefix: "mimic-iv-ed/2.2/ed/"
    edstays: "edstays.csv.gz"
    diagnosis: "diagnosis.csv.gz"
    pyxis: "pyxis.csv.gz"
    triage: "triage.csv.gz"
    vitalsign: "vitalsign.csv.gz"
    medrecon: "medrecon.csv.gz"

  mimic_iv:
    prefix: "files/mimiciv/2.2/hosp/"
    admissions: "admissions.csv.gz"
    patients: "patients.csv.gz"
    transfers: "transfers.csv.gz"
    labevents: "labevents.csv.gz"
    prescriptions: "prescriptions.csv.gz"
    diagnoses_icd: "diagnoses_icd.csv.gz"
    procedures_icd: "procedures_icd.csv.gz"
    d_icd_diagnoses: "d_icd_diagnoses.csv.gz"
    d_icd_procedures: "d_icd_procedures.csv.gz"
    d_labitems: "d_labitems.csv.gz"

  mimic_icu:
    prefix: "files/mimiciv/2.2/icu/"
    icustays: "icustays.csv.gz"
    chartevents: "chartevents.csv.gz"
    d_items: "d_items.csv.gz"
    inputevents: "inputevents.csv.gz"
    outputevents: "outputevents.csv.gz"
    procedureevents: "procedureevents.csv.gz"