# preprocessing_config.yaml
# Configuration for MIMIC preprocessing pipeline

preprocessing:
  # Phase 1: Stay ID Identification
  phase1:
    # Size of chunks for parallel processing
    chunk_size: 10000
    
    # Extended window (days) for matching CXR to ED stays after discharge
    extended_window_days: 7
    
    # Whether to process all CXRs or only frontal views
    view_filter: 'all'  # Options: 'all', 'frontal', 'lateral'
  
  # Phase 2: Clinical Data Extraction
  phase2:
    # Time windows for data extraction (hours before CXR)
    lab_lookback_hours: 24
    medication_lookback_hours: 48
    vitals_lookback_hours: 24
    
    # Chunk sizes for reading large files
    lab_chunk_size: 100000
    chart_chunk_size: 100000
    prescription_chunk_size: 50000
    
    # Data extraction flags (set to false to skip)
    extract_labs: true
    extract_medications: true
    extract_diagnoses: true
    extract_procedures: true
    extract_vitals: true
    extract_radiology_reports: false  # Requires additional setup
    
    # Lab configuration
    important_lab_items:
      # Complete Blood Count
      - itemid: 51221
        name: 'Hematocrit'
      - itemid: 51222
        name: 'Hemoglobin'
      - itemid: 51265
        name: 'Platelet Count'
      - itemid: 51301
        name: 'White Blood Cells'
      
      # Basic Metabolic Panel
      - itemid: 50912
        name: 'Creatinine'
      - itemid: 50971
        name: 'Potassium'
      - itemid: 50983
        name: 'Sodium'
      - itemid: 50902
        name: 'Chloride'
      - itemid: 50882
        name: 'Bicarbonate'
      - itemid: 50931
        name: 'Glucose'
      - itemid: 51006
        name: 'Urea Nitrogen'
      
      # Cardiac Markers
      - itemid: 51003
        name: 'Troponin T'
      - itemid: 50911
        name: 'CK-MB'
      - itemid: 50963
        name: 'NTproBNP'
      
      # Inflammatory Markers
      - itemid: 50889
        name: 'C-Reactive Protein'
      - itemid: 51146
        name: 'Procalcitonin'
      
      # Coagulation
      - itemid: 51237
        name: 'INR'
      - itemid: 51274
        name: 'PT'
      - itemid: 51275
        name: 'PTT'
      
      # Other Important Labs
      - itemid: 50813
        name: 'Lactate'
      - itemid: 50820
        name: 'pH'
      - itemid: 50818
        name: 'pCO2'
      - itemid: 50816
        name: 'pO2'
    
    # Vital signs configuration
    vital_sign_items:
      - itemid: 220045
        name: 'Heart Rate'
      - itemid: 220210
        name: 'Respiratory Rate'
      - itemid: 220277
        name: 'SpO2'
      - itemid: 220179
        name: 'Systolic BP (Non-invasive)'
      - itemid: 220180
        name: 'Diastolic BP (Non-invasive)'
      - itemid: 223761
        name: 'Temperature (F)'
      - itemid: 223762
        name: 'Temperature (C)'
      - itemid: 220228
        name: 'Respiratory Rate (Total)'
      - itemid: 220181
        name: 'Mean BP (Non-invasive)'
    
    # Medication categories to identify
    medication_categories:
      antibiotics:
        - 'cillin'
        - 'mycin'
        - 'floxacin'
        - 'cephalexin'
        - 'cefazolin'
        - 'ceftriaxone'
        - 'azithromycin'
        - 'metronidazole'
        - 'vancomycin'
        - 'meropenem'
      vasopressors:
        - 'norepinephrine'
        - 'epinephrine'
        - 'dopamine'
        - 'vasopressin'
        - 'phenylephrine'
      anticoagulants:
        - 'heparin'
        - 'warfarin'
        - 'enoxaparin'
        - 'rivaroxaban'
        - 'apixaban'
    
    # Maximum number of chunks to process per file
    max_chunks_per_file: 50
    
    # Sample size for testing (set to null for full processing)
    test_sample_size: null
  
  # Phase 3: Integration
  phase3:
    # Whether to copy CXR images to patient folders
    copy_images: true
    
    # Image format to copy
    image_format: 'jpg'  # Options: 'jpg', 'dcm'
    
    # Whether to create individual patient folders
    create_patient_folders: true
    
    # Output formats
    save_json: true  # Preserves nested structure
    save_csv: true   # Flattened for easier querying
    save_parquet: false  # Efficient columnar format
    
    # Data to include in patient folders
    include_clinical: true
    include_labs: true
    include_medications: true
    include_diagnoses: true
    include_procedures: true
    include_reports: false  # Set to true if radiology reports available

# Processing configuration
processing:
  # Number of parallel workers for chunked processing
  parallel_workers: 4
  
  # Memory limit per worker (MB)
  memory_limit_mb: 8192
  
  # Whether to use AWS Athena for large file queries
  use_athena: false
  athena_database: 'mimic'
  athena_workgroup: 'primary'
  athena_output_location: 's3://your-athena-results-bucket/'
  
  # Whether to use a database instead of direct file reading
  use_database: false
  database_type: 'postgresql'  # Options: 'postgresql', 'mysql', 'sqlite'
  database_config:
    host: 'localhost'
    port: 5432
    database: 'mimic'
    username: 'mimic_user'
    password: ''  # Use environment variable DB_PASSWORD

# Data quality configuration
data_quality:
  # Minimum data requirements for a record to be included
  require_clinical_features: false
  require_labs: false
  require_medications: false
  
  # Data validation
  validate_dates: true
  validate_ids: true
  remove_duplicates: true
  
  # Outlier detection
  detect_outliers: true
  outlier_method: 'iqr'  # Options: 'iqr', 'zscore'
  outlier_threshold: 3

# Logging configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR
  level: 'INFO'
  
  # Log directory
  directory: 'logs'
  
  # Log file rotation
  rotation_size: '500 MB'
  retention_days: 10
  
  # Whether to log to console
  console_output: true
  
  # Whether to save processing statistics
  save_statistics: true
  statistics_file: 'processing_stats.json'

# Error handling
error_handling:
  # Whether to continue on errors
  continue_on_error: true
  
  # Maximum errors before stopping
  max_errors: 100
  
  # Whether to save error records for review
  save_error_records: true
  error_file: 'processing_errors.csv'
  
  # Retry configuration
  retry_failed: true
  max_retries: 3
  retry_delay_seconds: 60