preprocessing:
  phase1:
    extended_window_days: 7
    chunk_size: 100  # Small for testing
    parallel_chunks: false
  
  phase2:
    lab_lookback_hours: 24
    medication_lookback_hours: 48
  
  phase3:
    create_patient_folders: true
    copy_images: false  # Don't copy images for testing
    image_format: jpg